#!/usr/bin/env python3
import json
import os
import re

def get_color(qml, prop_name, default="#000000"):
    # Match both 'readonly property color' and 'property color'
    m = re.search(r'property\s+color\s+' + prop_name + r'\s*:\s*"#([0-9a-fA-F]{6,8})"', qml)
    if m:
        hex_val = m.group(1)
        # Kitty prefers #RRGGBB, drop alpha if it's 8 chars
        if len(hex_val) == 8:
            return f"#{hex_val[:6]}"
        return f"#{hex_val}"
    return default

home = os.environ.get("HOME", "/home/grey")
theme_json_path = os.path.join(home, ".config/quickshell/colors/theme.json")

try:
    with open(theme_json_path, "r") as f:
        data = json.load(f)
        theme_name = data.get("theme", "Sepia")
except Exception:
    theme_name = "Sepia"

qml_path = os.path.join(home, f".config/quickshell/colors/themes/{theme_name}.qml")
try:
    with open(qml_path, "r") as f:
        qml_content = f.read()
except Exception as e:
    print(f"Error reading {qml_path}: {e}")
    exit(1)

bg = get_color(qml_content, "bg", "#000000")
fg = get_color(qml_content, "fg", "#ffffff")
accent = get_color(qml_content, "accent", "#888888")
surfaceHigh = get_color(qml_content, "surfaceHigh", "#333333")
border = get_color(qml_content, "border", "#555555")

error = get_color(qml_content, "error", "#ff0000")
success = get_color(qml_content, "success", "#00ff00")
warning = get_color(qml_content, "warning", "#ffff00")
primary = get_color(qml_content, "primary", "#0000ff")
tertiary = get_color(qml_content, "tertiary", "#ff00ff")
secondary = get_color(qml_content, "secondary", "#00ffff")

kitty_conf_content = f"""# Auto-generated by update_kitty_theme.py
foreground {fg}
background {bg}
selection_foreground {bg}
selection_background {accent}
cursor {accent}
cursor_text_color {bg}
url_color {accent}
active_border_color {accent}
inactive_border_color {border}
bell_border_color {warning}

# ANSI colors
color0 {bg}
color1 {error}
color2 {success}
color3 {warning}
color4 {primary}
color5 {tertiary}
color6 {secondary}
color7 {fg}

# Bright colors
color8 {surfaceHigh}
color9 {error}
color10 {success}
color11 {warning}
color12 {accent}
color13 {tertiary}
color14 {secondary}
color15 {fg}
"""

kitty_dir = os.path.join(home, ".config/kitty")
os.makedirs(kitty_dir, exist_ok=True)
theme_conf_path = os.path.join(kitty_dir, "theme.conf")

with open(theme_conf_path, "w") as f:
    f.write(kitty_conf_content)

# Send SIGUSR1 to kitty instances to reload config
os.system("killall -SIGUSR1 kitty 2>/dev/null")
